version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: pylint
    versions:
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.8.1
  - dependency-name: docutils
    versions:
    - "0.17"
    - 0.17.1
  - dependency-name: django-extra-checks
    versions:
    - 0.10.0
    - 0.11.0
    - 0.9.1
  - dependency-name: drf-spectacular
    versions:
    - 0.13.2
    - 0.15.0
    - 0.15.1
  - dependency-name: django-debug-toolbar
    versions:
    - 3.2.1
  - dependency-name: django
    versions:
    - "3.2"
    - 3.2rc1
  - dependency-name: django-jazzmin
    versions:
    - 2.4.5
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
    - 8.2.0
  - dependency-name: dj-rest-auth
    versions:
    - 2.1.4
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
    - 3.12.4
  - dependency-name: pycodestyle
    versions:
    - 2.7.0
