DEBUG: False
SECRET_KEY: d;safldsvbas;vbakvjbdskvdkgbaksdbsdkajsbkaklsdfbdasf
ALLOWED_HOSTS:
  - localhost
  - 127.0.0.1
CORS_ORIGIN_WHITELIST:
  - http://localhost:4200
SITE_TITLE: Formidable
SITE_HEADER: Formidable
INDEX_TITLE: Formidable
DB_NAME:
DB_USER:
DB_PASSWORD:
DB_HOST:
DB_PORT:
THUMBNAIL_SIZE:
DEFAULT_FROM_EMAIL:
EMAIL_HOST_USER:
EMAIL_HOST_PASSWORD:
