# Generated by Django 3.1.5 on 2021-01-20 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='form name')),
                (
                    'description',
                    models.TextField(
                        blank=True, default='', max_length=500, verbose_name='form description'
                    ),
                ),
                ('button_text', models.CharField(max_length=50, verbose_name='submit button text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='field name')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('text', 'text'),
                            ('email', 'email'),
                            ('url', 'url'),
                            ('file', 'file'),
                            ('integer', 'integer'),
                            ('decimal', 'decimal'),
                            ('tel', 'phone number'),
                            ('date', 'date'),
                            ('time', 'time'),
                            ('datetime', 'datetime'),
                            ('radio', 'radio'),
                            ('checkbox', 'checkbox'),
                            ('select', 'select'),
                        ],
                        default='text',
                        max_length=50,
                        verbose_name='field type',
                    ),
                ),
                (
                    'placeholder',
                    models.CharField(
                        blank=True, default='', max_length=200, verbose_name='placeholder'
                    ),
                ),
                (
                    'dependent_value',
                    models.CharField(
                        blank=True, default='', max_length=200, verbose_name='with value'
                    ),
                ),
                (
                    'dependent_field',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'type__in': ['select', 'checkbox', 'radio']},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dependents',
                        related_query_name='dependent',
                        to='formidable.formfield',
                        verbose_name='depends on',
                    ),
                ),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fields',
                        related_query_name='field',
                        to='formidable.form',
                        verbose_name='form this filed belongs to',
                    ),
                ),
            ],
            options={
                'db_table': 'fields',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    model_utils.fields.StatusField(
                        choices=[('new', 'new'), ('err', 'has errors'), ('ok', 'ok')],
                        default='new',
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name='status',
                    ),
                ),
                (
                    'status_changed',
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor='status',
                        verbose_name='status changed',
                    ),
                ),
                (
                    'form',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='formidable.form',
                        verbose_name='form this response belongs to',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('minlength', 'min length'),
                            ('maxlength', 'max length'),
                            ('regex', 'regex'),
                        ],
                        default=None,
                        max_length=10,
                    ),
                ),
                ('constraint', models.CharField(max_length=500)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('inverse_match', models.BooleanField()),
                (
                    'flags',
                    models.CharField(
                        blank=True,
                        choices=[
                            (2, 'case-insensitive'),
                            (8, 'multiline'),
                            (16, 'dotall'),
                            (32, 'unicode'),
                        ],
                        default='',
                        max_length=5,
                    ),
                ),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validators',
                        related_query_name='validator',
                        to='formidable.formfield',
                        verbose_name='field to validate',
                    ),
                ),
            ],
            options={
                'db_table': 'validators',
            },
        ),
        migrations.CreateModel(
            name='ResponseField',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    model_utils.fields.StatusField(
                        choices=[('new', 'new'), ('err', 'has errors'), ('ok', 'ok')],
                        default='new',
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name='status',
                    ),
                ),
                (
                    'status_changed',
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor='status',
                        verbose_name='status changed',
                    ),
                ),
                ('value', models.CharField(max_length=500, verbose_name='value')),
                (
                    'errors',
                    models.CharField(blank=True, default='', max_length=500, verbose_name='errors'),
                ),
                (
                    'observations',
                    models.CharField(
                        blank=True, default='', max_length=500, verbose_name='observations'
                    ),
                ),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='formidable.formfield',
                        verbose_name='field this response belongs to',
                    ),
                ),
                (
                    'response',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fields',
                        related_query_name='field',
                        to='formidable.response',
                        verbose_name='application this response belongs to',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=300, verbose_name='choice name')),
                (
                    'fields',
                    models.ManyToManyField(
                        limit_choices_to={'type__in': ['select', 'checkbox', 'radio']},
                        related_name='choices',
                        related_query_name='choice',
                        to='formidable.FormField',
                        verbose_name='"select" form fields',
                    ),
                ),
            ],
            options={
                'db_table': 'choices',
            },
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.CheckConstraint(
                check=models.Q(type__in=['minlength', 'maxlength', 'regex']),
                name='validator_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.CheckConstraint(
                check=models.Q(flags__in=['', 2, 8, 16, 32]), name='validator_flag_valid'
            ),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.CheckConstraint(
                check=models.Q(
                    type__in=[
                        'text',
                        'email',
                        'url',
                        'file',
                        'integer',
                        'decimal',
                        'tel',
                        'date',
                        'time',
                        'datetime',
                        'radio',
                        'checkbox',
                        'select',
                    ]
                ),
                name='form_field_type_valid',
            ),
        ),
    ]
