# Generated by Django 3.1.5 on 2021-01-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formfield",
            name="form_field_type_valid",
        ),
        migrations.RenameField(
            model_name="responsefield",
            old_name="response",
            new_name="application",
        ),
        migrations.AlterField(
            model_name="choice",
            name="fields",
            field=models.ManyToManyField(
                limit_choices_to={"type__in": ["select", "checkbox", "radio"]},
                related_name="choices",
                related_query_name="choice",
                to="formidable.FormField",
                verbose_name="fields",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="button_text",
            field=models.CharField(
                default="Submit", max_length=50, verbose_name="submit button text"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                related_query_name="field",
                to="formidable.form",
                verbose_name="related form",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "text"),
                    ("email", "email"),
                    ("url", "url"),
                    ("file", "file"),
                    ("integer", "integer"),
                    ("decimal", "decimal"),
                    ("tel", "phone number"),
                    ("date", "date"),
                    ("time", "time"),
                    ("datetime", "datetime"),
                    ("radio", "radio"),
                    ("checkbox", "checkbox"),
                    ("select", "select"),
                ],
                default="text",
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                related_query_name="application",
                to="formidable.form",
                verbose_name="form this response belongs to",
            ),
        ),
        migrations.AlterField(
            model_name="responsefield",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                related_query_name="response",
                to="formidable.formfield",
                verbose_name="field this response belongs to",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="constraint",
            field=models.CharField(max_length=500, verbose_name="constraint"),
        ),
        migrations.AlterField(
            model_name="validator",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="flags",
            field=models.CharField(
                blank=True,
                choices=[
                    (2, "case-insensitive"),
                    (8, "multiline"),
                    (16, "dotall"),
                    (32, "unicode"),
                ],
                default="",
                max_length=5,
                verbose_name="flags",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="inverse_match",
            field=models.BooleanField(verbose_name="inverse match"),
        ),
        migrations.AlterField(
            model_name="validator",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="is enabled"),
        ),
        migrations.AlterField(
            model_name="validator",
            name="message",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="message"
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="type",
            field=models.CharField(
                choices=[
                    ("minlength", "min length"),
                    ("maxlength", "max length"),
                    ("regex", "regex"),
                ],
                default=None,
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.CheckConstraint(
                check=models.Q(
                    type__in=[
                        "text",
                        "email",
                        "url",
                        "file",
                        "integer",
                        "decimal",
                        "tel",
                        "date",
                        "time",
                        "datetime",
                        "radio",
                        "checkbox",
                        "select",
                    ]
                ),
                name="field_type_valid",
            ),
        ),
        migrations.AlterModelTable(
            name="form",
            table="forms",
        ),
        migrations.AlterModelTable(
            name="response",
            table="applications",
        ),
        migrations.AlterModelTable(
            name="responsefield",
            table="responses",
        ),
    ]
