# Generated by Django 3.1.5 on 2021-01-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0003_auto_20210121_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseField',
            new_name='Response',
        ),
    ]
