# Generated by Django 3.1.5 on 2021-01-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0004_auto_20210121_2205"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Form",
            new_name="FormSection",
        ),
        migrations.RenameField(
            model_name="formfield",
            old_name="form",
            new_name="form_section",
        ),
    ]
