# Generated by Django 3.1.5 on 2021-01-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0005_auto_20210130_1206"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formsection",
            options={
                "verbose_name": "form section",
                "verbose_name_plural": "form sections",
            },
        ),
        migrations.AlterField(
            model_name="formfield",
            name="form_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                related_query_name="field",
                to="formidable.formsection",
                verbose_name="related form section",
            ),
        ),
        migrations.AlterField(
            model_name="formsection",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="section description",
            ),
        ),
        migrations.AlterField(
            model_name="formsection",
            name="name",
            field=models.CharField(max_length=200, verbose_name="section name"),
        ),
        migrations.AlterModelTable(
            name="formsection",
            table="form_sections",
        ),
    ]
