# Generated by Django 3.1.5 on 2021-01-30 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0006_auto_20210130_1315"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="form name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="form description",
                    ),
                ),
            ],
            options={
                "verbose_name": "form",
                "verbose_name_plural": "forms",
                "db_table": "forms",
            },
        ),
        migrations.AlterField(
            model_name="formsection",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="section name"
            ),
        ),
        migrations.AddField(
            model_name="formsection",
            name="form",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                related_query_name="section",
                to="formidable.form",
                verbose_name="related form",
            ),
            preserve_default=False,
        ),
    ]
