# Generated by Django 3.2.2 on 2021-05-11 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formidable', '0012_alter_response_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', related_query_name='application', to='administration.user', verbose_name='applicant'),
            preserve_default=False,
        ),
    ]
