# Generated by Django 3.2.3 on 2021-05-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0013_application_applicant"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FormField",
            new_name="Field",
        ),
        migrations.RenameModel(
            old_name="FormSection",
            new_name="Section",
        ),
    ]
