# Generated by Django 3.2.3 on 2021-05-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0014_auto_20210516_0119"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name": "section", "verbose_name_plural": "sections"},
        ),
        migrations.RenameField(
            model_name="field", old_name="form_section", new_name="section"
        ),
        migrations.AlterField(
            model_name="field",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                related_query_name="field",
                to="formidable.section",
                verbose_name="section",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choice",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                related_query_name="section",
                to="formidable.form",
                verbose_name="form",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="name"
            ),
        ),
    ]
