# Generated by Django 3.2.3 on 2021-05-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0016_alter_application_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="inverse_match",
            field=models.BooleanField(default=False, verbose_name="inverse match"),
        ),
        migrations.AlterField(
            model_name="validator",
            name="type",
            field=models.CharField(
                choices=[
                    ("min", "Minimum value (applies to number inputs only)"),
                    ("max", "Maximum value (applies to number inputs only)"),
                    ("minlength", "Minimum length"),
                    ("maxlength", "Maximum length"),
                    ("email", "Email"),
                    ("pattern", "Regular expression"),
                ],
                default="minlength",
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
