# Generated by Django 3.2.3 on 2021-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0017_auto_20210518_0236"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="is_required",
            field=models.BooleanField(default=False, verbose_name="is required"),
        ),
    ]
