# Generated by Django 3.2.6 on 2021-08-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0018_field_is_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["order_index"],
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
        migrations.AddField(
            model_name="section",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
