# Generated by Django 3.2.6 on 2021-08-31 16:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0019_auto_20210831_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                related_query_name="application",
                to="formidable.form",
                verbose_name="form",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                related_query_name="response",
                to="formidable.application",
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                related_query_name="response",
                to="formidable.field",
                verbose_name="field",
            ),
        ),
    ]
