# Generated by Django 3.2.6 on 2021-08-31 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formidable", "0020_auto_20210831_1908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, default="", max_length=5000, verbose_name="description"
            ),
        ),
    ]
