# Generated by Django 3.2.6 on 2021-08-31 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0021_alter_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=1000, verbose_name='description'),
        ),
    ]
